### ISSUE TITLE
[BUG]: [Chatextras] Icons and username disappear after activation

### ISSUE THREAD

**Issue by Suchty112** [LSS-Manager/LSSM-V.4#214]
**Describe what happens**
the @ and /w symbol and username have been removed by activating chat extras

**How to reproduce?**
Activate the new addon chatextras

**Expected behavior**
What did you expect LSS-Manager to do?

**Screenshots**
![blob](https://cdn.discordapp.com/attachments/526011090933383189/773680574933368862/unknown.png)
![blob](https://cdn.discordapp.com/attachments/361252714006446092/773682528343031808/unknown.png)
**Further notes: *(please complete)***
 - OS: windoof 10
 - Browser: chrome
 - LSSM-Version: 4.0.6+20201104.2234%c
 - for Smartphones / Tablets: your device: /
 - which of the games are you playing: meldkamerspel
 - your ingame name: SanniHameln

**Further**
Add further notes here

**Comment by JRH-1997** [comment]
Also the username is removed

**Comment by JRH-1997** [comment]
A possible solution:
Change:
messageHeader.innerText = '[' + timeStampModified + ']';
to:
messageHeader.firstChild.textContent = '[' + timeStampModified + '] ';

Don't forget the spaces for the space between date and first icon

**Comment by JRH-1997** [comment]
Also new messages aren't edited 
![afbeelding](https://user-images.githubusercontent.com/65117490/98180493-4f40b080-1f01-11eb-8f32-ca43434b5625.png)

**Comment by jxn-30** [comment]
For new messages, `date` instead of `date_hidden` needs to be modified.
For existing chatMessages, we could get the textNode which is `[XX:XX]` and modify that one. Should be the easiest way to do that.
A way to get all TextNodes within a specific element can be found in `/src/utils` if I do remember that correctly. However the generalExtensions' setting "clickableLinks" makes use of such a function. Maybe we just need to adjust that one to make recursive node finding optional :)

**Comment by Cr4zyc4k3** [comment]
Should be fixed with https://github.com/LSS-Manager/LSSM-V.4/commit/e904775918d94376782901b4a94f9fd8470bbfb1

**Comment by jxn-30** [comment]
Done with #220 
if further issues are detected, reopen or create new issue!
