### ISSUE TITLE
[Feature request]: Staffing view in dashboard

### ISSUE THREAD

**Issue by bagman002** [LSS-Manager/LSSM-V.4#2257]
### Is your feature related to a problem?

No

### Solution / Feature

I would like to see the option to view staff within the dashboard to better understand and assess what stations need what training and backfill lacking knowledge.

Currently you can see what stations have what extensions but not what staff you have and their current skilling

### Additional

It would also be great for this to be exported as a CSV including the building overview to include building name and location for future planning and development into what needs upgrading next

**Comment by jxn-30** [comment]
We would love that too!
Unfortunately, there is no generally acceptable way to create a staff overview. Or at least we have not found a way yet!

**Why?**
There will not be an API from game side as the amount of data would be too huge. There are players with multiple millions of staff. That would not only be a massive amount of data that needs to be transferred but it also takes the game relatively long to gather the information and put them into an API.
We could gather the data ourselfes but that costs a server request for each station. As we have to wait at least 100ms between sending two server requests, that means you would have to wait one second per 10 stations. The time that is required to gather the information will be pretty long for larger players. Also we again do have the problem with amount and size of data: Your browser somehow needs to store the data so that LSSM can work with it.

I would also love to have an overview over my staff but I unfortunately don't see a way to implement that in a way that not only smaller players but also medium and large players can use it.

This issue will be closed as not planned here because I can only choose between "close as completed" and "close as not planned", although the feature actually is planned since long time but we don't know how to implement as stated above.

**Comment by Cr4zyc4k3** [comment]
Sure, thats just a simple json to csv conversion. But since that is not related here please open another issue.

**Comment by jxn-30** [comment]
That is possible but it would be best to open a new issue for this or put the request in #12 as it is related to the Dashboard-Module.
Please provide some example on how you would like to have the CSV structured. There is already a CSV-Export on the charts but that doesn't cover extensions.
