### ISSUE TITLE
[Feature request]: Vehicle Display limited - Load missing

### ISSUE THREAD

**Issue by bagman002** [LSS-Manager/LSSM-V.4#2418]
### Is your feature related to a problem?

I was wondering if it would be at all possible to have the addon click this banner when shown 
![image](https://github.com/LSS-Manager/LSSM-V.4/assets/66065321/8e89f05d-3f62-45dd-b61b-615f5cf12ded)

### Solution / Feature

When yellow banner vehicle display limited is shown click button to refresh vehicle selection. For players with lots of resources this is helpful to show some of the more distant units when responding to calls.

**Comment by Cr4zyc4k3** [comment]
The button was implemented after the mission loading took ages (3-4 seconds) for people with many vehicles. Building a function which enables automatic loading of missing vehicles would defeat the whole purpose of this button.

**Comment by bagman002** [comment]
My appoligies I didn't see it as being an automatic action. With that in mind does that not mean the transport helper would also be against TOS. As it is even described as clicking the button automatically?

![image](https://github.com/LSS-Manager/LSSM-V.4/assets/66065321/e523247e-0f0d-4f22-b04e-05ccd9657642)

**Comment by jxn-30** [comment]
when there's a (potential) feature that we're unsure of wether it is against TOS, we're always asking the Game-Devs and that feature has been approved by them. I expect this to be because it does not add as much additional Server-Load as the orange "vehicle display limited" button does.

There are indeed some features where one could argue for both sides "ok with TOS" and "against TOS". For those features we're always asking to be sure, as we're not the ones in charge to decide that.

**Comment by bagman002** [comment]
That's fair thank you for taking the time to clarify
